### ISSUE TITLE
error in passenger profile page layout 

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [krishr2d2/ITS_Project#10]
![screenshot from 2017-03-01 17-58-23](https://cloud.githubusercontent.com/assets/16081083/23459995/df82a900-fea8-11e6-9ec3-659725261a94.png)

* a div with id page-wrapper has to be removed

**Comment by krishr2d2** [comment]
Possibly in the passenger.html file......there is already a page-wrapper included in the base.html. The passenger.html extends the base.html.
